server:
  port: 14888

logging:
  level:
    root: info
    com.ceiec.gis.springboot.mapper: debug

spring:
  datasource:
    url: jdbc:postgresql://192.168.19.57:5432/kyrgyzstan_v2
    username: postgres
    password: 1234
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

