package com.m.gis.springboot.po;

import org.postgis.MultiLineString;

import java.math.BigDecimal;

public class GisAngolaRoad {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.gid
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.objectid
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private Integer objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.name
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.code
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.roadname
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private String roadname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.length
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private BigDecimal length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.shape_leng
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private BigDecimal shapeLeng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis_angola_road_l.geom
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    private MultiLineString geom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.gid
     *
     * @return the value of gis_angola_road_l.gid
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.gid
     *
     * @param gid the value for gis_angola_road_l.gid
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.objectid
     *
     * @return the value of gis_angola_road_l.objectid
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public Integer getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.objectid
     *
     * @param objectid the value for gis_angola_road_l.objectid
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setObjectid(Integer objectid) {
        this.objectid = objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.name
     *
     * @return the value of gis_angola_road_l.name
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.name
     *
     * @param name the value for gis_angola_road_l.name
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.code
     *
     * @return the value of gis_angola_road_l.code
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.code
     *
     * @param code the value for gis_angola_road_l.code
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.roadname
     *
     * @return the value of gis_angola_road_l.roadname
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public String getRoadname() {
        return roadname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.roadname
     *
     * @param roadname the value for gis_angola_road_l.roadname
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setRoadname(String roadname) {
        this.roadname = roadname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.length
     *
     * @return the value of gis_angola_road_l.length
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.length
     *
     * @param length the value for gis_angola_road_l.length
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.shape_leng
     *
     * @return the value of gis_angola_road_l.shape_leng
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public BigDecimal getShapeLeng() {
        return shapeLeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.shape_leng
     *
     * @param shapeLeng the value for gis_angola_road_l.shape_leng
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setShapeLeng(BigDecimal shapeLeng) {
        this.shapeLeng = shapeLeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis_angola_road_l.geom
     *
     * @return the value of gis_angola_road_l.geom
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public MultiLineString getGeom() {
        return geom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis_angola_road_l.geom
     *
     * @param geom the value for gis_angola_road_l.geom
     *
     * @mbg.generated Wed Jan 03 16:27:38 CST 2018
     */
    public void setGeom(MultiLineString geom) {
        this.geom = geom;
    }
}